export enum CommandGroup {
  Anx,
  AnxCommon,
  Git,
  GitDiff,
  GitFetch,
}

export enum OptionKind {
  Flag,
  RepeatableFlag,
  Stuck,
  OptionalStuck,
  KeyValue,
  CommaDelimitedKeyValue,
  RepeatableKeyValue,
  AnonymousKeyValue,
  Numeric,
  OptionalNumeric,
  NumericParam,
  Date,
  String,
  OptionalString,
  StringParam,
  OptionalStringParam,
  CommaDelimitedStrings,
  OptionalCommaDelimitedStrings,
  RepeatableString,
  RepeatableOptionalString,
  RepeatableOptionalStringParam,
  AnonymousStrings,
  NamedStrings,
  RepeatablePath,
}

export interface CommandOption {
  name: string;
  kind: OptionKind;
}

const anxCommandOptions: Map<string, CommandOption[]> = new Map([
  ['_common', [
    { name: '--c', kind: OptionKind.RepeatableKeyValue },
    { name: '--debug', kind: OptionKind.Flag },
    { name: '--debugfilter', kind: OptionKind.CommaDelimitedStrings },
    { name: '--fast', kind: OptionKind.Flag },
    { name: '--force', kind: OptionKind.Flag },
    { name: '--mincopies', kind: OptionKind.Numeric },
    { name: '--no-debug', kind: OptionKind.Flag },
    { name: '--numcopies', kind: OptionKind.Numeric },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--size-limit', kind: OptionKind.String },
    { name: '--time-limit', kind: OptionKind.String },
    { name: '--verbose', kind: OptionKind.Flag },
  ]],
  ['add', [
    { name: '--backend', kind: OptionKind.String },
    { name: '--dry-run', kind: OptionKind.Flag },
    { name: '--force-large', kind: OptionKind.Flag },
    { name: '--force-small', kind: OptionKind.Flag },
    { name: '--jobs', kind: OptionKind.Numeric },
    { name: '--json', kind: OptionKind.Flag },
    { name: '--json-error-messages', kind: OptionKind.Flag },
    { name: '--json-progress', kind: OptionKind.Flag },
    { name: '--no-check-gitignore', kind: OptionKind.Flag },
    { name: '--update', kind: OptionKind.Flag },
    { name: 'matching', kind: OptionKind.AnonymousStrings },
  ]],
  ['adjust', [
    { name: '--fix', kind: OptionKind.Flag },
    { name: '--hide-missing', kind: OptionKind.Flag },
    { name: '--lock', kind: OptionKind.Flag },
    { name: '--unlock', kind: OptionKind.Flag },
    { name: '--unlock-present', kind: OptionKind.Flag },
  ]],
  ['config', [
    { name: '--get', kind: OptionKind.String },
    { name: '--set', kind: OptionKind.KeyValue },
    { name: '--unset', kind: OptionKind.String },
  ]],
  ['copy', [
    { name: '--all', kind: OptionKind.Flag },
    { name: '--auto', kind: OptionKind.Flag },
    { name: '--branch', kind: OptionKind.String },
    { name: '--failed', kind: OptionKind.Flag },
    { name: '--from', kind: OptionKind.String },
    { name: '--jobs', kind: OptionKind.Numeric },
    { name: '--json', kind: OptionKind.Flag },
    { name: '--json-error-messages', kind: OptionKind.Flag },
    { name: '--json-progress', kind: OptionKind.Flag },
    { name: '--key', kind: OptionKind.String },
    { name: '--to', kind: OptionKind.String },
    { name: '--unused', kind: OptionKind.Flag },
    { name: 'matching', kind: OptionKind.AnonymousStrings },
  ]],
  ['dead', []],
  ['describe', []],
  ['drop', [
    { name: '--all', kind: OptionKind.Flag },
    { name: '--auto', kind: OptionKind.Flag },
    { name: '--branch', kind: OptionKind.String },
    { name: '--from', kind: OptionKind.String },
    { name: '--jobs', kind: OptionKind.Numeric },
    { name: '--json', kind: OptionKind.Flag },
    { name: '--json-error-messages', kind: OptionKind.Flag },
    { name: '--key', kind: OptionKind.String },
    { name: '--unused', kind: OptionKind.Flag },
    { name: 'matching', kind: OptionKind.AnonymousStrings },
  ]],
  ['dropunused', [
    { name: '--from', kind: OptionKind.String },
  ]],
  ['enableremote', []],
  ['expire', [
    { name: '--activity', kind: OptionKind.String },
    { name: '--no-act', kind: OptionKind.Flag },
  ]],
  ['find', [
    { name: '--branch', kind: OptionKind.String },
    { name: '--format', kind: OptionKind.String },
    { name: '--json', kind: OptionKind.Flag },
    { name: '--json-error-messages', kind: OptionKind.Flag },
    { name: 'matching', kind: OptionKind.AnonymousStrings },
  ]],
  ['fsck', [
    { name: '--all', kind: OptionKind.Flag },
    { name: '--branch', kind: OptionKind.String },
    { name: '--from', kind: OptionKind.String },
    { name: '--incremental', kind: OptionKind.Flag },
    { name: '--incremental-schedule', kind: OptionKind.String },
    { name: '--jobs', kind: OptionKind.Numeric },
    { name: '--json', kind: OptionKind.Flag },
    { name: '--key', kind: OptionKind.String },
    { name: '--more', kind: OptionKind.Flag },
    { name: '--unused', kind: OptionKind.Flag },
    { name: 'matching', kind: OptionKind.AnonymousStrings },
  ]],
  ['get', [
    { name: '--all', kind: OptionKind.Flag },
    { name: '--auto', kind: OptionKind.Flag },
    { name: '--branch', kind: OptionKind.String },
    { name: '--failed', kind: OptionKind.Flag },
    { name: '--from', kind: OptionKind.String },
    { name: '--incomplete', kind: OptionKind.Flag },
    { name: '--jobs', kind: OptionKind.Numeric },
    { name: '--json', kind: OptionKind.Flag },
    { name: '--json-error-messages', kind: OptionKind.Flag },
    { name: '--json-progress', kind: OptionKind.Flag },
    { name: '--key', kind: OptionKind.String },
    { name: '--unused', kind: OptionKind.Flag },
    { name: 'matching', kind: OptionKind.AnonymousStrings },
  ]],
  ['group', []],
  ['groupwanted', []],
  ['info', [
    { name: '--autoenable', kind: OptionKind.Flag },
    { name: '--bytes', kind: OptionKind.Flag },
    { name: '--json', kind: OptionKind.Flag },
    { name: '--json-error-messages', kind: OptionKind.Flag },
    { name: 'matching', kind: OptionKind.AnonymousStrings },
  ]],
  ['init', [
    { name: '--autoenable', kind: OptionKind.Flag },
    { name: '--no-autoenable', kind: OptionKind.Flag },
    { name: '--version', kind: OptionKind.Numeric },
  ]],
  ['initremote', [
    { name: '--private', kind: OptionKind.Flag },
    { name: '--sameas', kind: OptionKind.String },
    { name: '--whatelse', kind: OptionKind.Flag },
  ]],
  ['list', [
    { name: '--allrepos', kind: OptionKind.Flag },
    { name: 'matching', kind: OptionKind.AnonymousStrings },
  ]],
  ['lock', [
    { name: '--json', kind: OptionKind.Flag },
    { name: '--json-error-messages', kind: OptionKind.Flag },
    { name: 'matching', kind: OptionKind.AnonymousStrings },
  ]],
  ['merge', [
    { name: '--allow-unrelated-histories', kind: OptionKind.Flag },
    { name: '--no-allow-unrelated-histories', kind: OptionKind.Flag },
  ]],
  ['mincopies', []],
  ['move', [
    { name: '--all', kind: OptionKind.Flag },
    { name: '--branch', kind: OptionKind.String },
    { name: '--failed', kind: OptionKind.Flag },
    { name: '--from', kind: OptionKind.String },
    { name: '--jobs', kind: OptionKind.Numeric },
    { name: '--json', kind: OptionKind.Flag },
    { name: '--json-error-messages', kind: OptionKind.Flag },
    { name: '--json-progress', kind: OptionKind.Flag },
    { name: '--key', kind: OptionKind.String },
    { name: '--to', kind: OptionKind.String },
    { name: '--unused', kind: OptionKind.Flag },
    { name: 'matching', kind: OptionKind.AnonymousStrings },
  ]],
  ['numcopies', []],
  ['reinit', []],
  ['renameremote', []],
  ['repair', []],
  ['required', []],
  ['semitrust', []],
  ['status', [
    { name: '--ignore-submodules', kind: OptionKind.OptionalString },
    { name: '--json', kind: OptionKind.Flag },
    { name: '--json-error-messages', kind: OptionKind.Flag },
  ]],
  ['sync', [
    { name: '--all', kind: OptionKind.Flag },
    { name: '--allow-unrelated-histories', kind: OptionKind.Flag },
    { name: '--backend', kind: OptionKind.String },
    { name: '--cleanup', kind: OptionKind.Flag },
    { name: '--commit', kind: OptionKind.Flag },
    { name: '--content', kind: OptionKind.Flag },
    { name: '--content-of', kind: OptionKind.RepeatablePath },
    { name: '--jobs', kind: OptionKind.Numeric },
    { name: '--message', kind: OptionKind.String },
    { name: '--no-allow-unrelated-histories', kind: OptionKind.Flag },
    { name: '--no-commit', kind: OptionKind.Flag },
    { name: '--no-content', kind: OptionKind.Flag },
    { name: '--no-pull', kind: OptionKind.Flag },
    { name: '--no-push', kind: OptionKind.Flag },
    { name: '--no-resolvemerge', kind: OptionKind.Flag },
    { name: '--not-only-annex', kind: OptionKind.Flag },
    { name: '--only-annex', kind: OptionKind.Flag },
    { name: '--pull', kind: OptionKind.Flag },
    { name: '--push', kind: OptionKind.Flag },
    { name: '--resolvemerge', kind: OptionKind.Flag },
  ]],
  ['unannex', [
    { name: 'matching', kind: OptionKind.AnonymousStrings },
  ]],
  ['ungroup', []],
  ['uninit', []],
  ['unlock', [
    { name: '--json', kind: OptionKind.Flag },
    { name: '--json-error-messages', kind: OptionKind.Flag },
    { name: 'matching', kind: OptionKind.AnonymousStrings },
  ]],
  ['untrust', []],
  ['unused', [
    { name: '--from', kind: OptionKind.String },
    { name: '--used-refspec', kind: OptionKind.String },
  ]],
  ['version', [
    { name: '--raw', kind: OptionKind.Flag },
  ]],
  ['wanted', []],
  ['whereis', [
    { name: '--all', kind: OptionKind.Flag },
    { name: '--branch', kind: OptionKind.String },
    { name: '--format', kind: OptionKind.String },
    { name: '--json', kind: OptionKind.Flag },
    { name: '--json-error-messages', kind: OptionKind.Flag },
    { name: '--key', kind: OptionKind.String },
    { name: '--unused', kind: OptionKind.Flag },
    { name: 'matching', kind: OptionKind.AnonymousStrings },
  ]],
  ['whereused', [
    { name: '--historical', kind: OptionKind.Flag },
    { name: '--key', kind: OptionKind.String },
    { name: '--unused', kind: OptionKind.Flag },
  ]],
]);

const gitCommandOptions: Map<string, CommandOption[]> = new Map([
  ['add', [
    { name: '--all', kind: OptionKind.Flag },
    { name: '--chmod', kind: OptionKind.String },
    { name: '--force', kind: OptionKind.Flag },
    { name: '--ignore-errors', kind: OptionKind.Flag },
    { name: '--intent-to-add', kind: OptionKind.Flag },
    { name: '--no-all', kind: OptionKind.Flag },
    { name: '--refresh', kind: OptionKind.Flag },
    { name: '--renormalize', kind: OptionKind.Flag },
    { name: '--sparse', kind: OptionKind.Flag },
    { name: '--update', kind: OptionKind.Flag },
    { name: '--verbose', kind: OptionKind.Flag },
  ]],
  ['branch', [
    // BranchListOptions
    { name: '--abbrev', kind: OptionKind.Numeric },
    { name: '--all', kind: OptionKind.Flag },
    { name: '--column', kind: OptionKind.OptionalCommaDelimitedStrings },
    { name: '--contains', kind: OptionKind.RepeatableOptionalStringParam },
    { name: '--format', kind: OptionKind.StringParam },
    { name: '--ignore-case', kind: OptionKind.Flag },
    { name: '--merged', kind: OptionKind.RepeatableOptionalStringParam },
    { name: '--no-abbrev', kind: OptionKind.Flag },
    { name: '--no-column', kind: OptionKind.Flag },
    { name: '--no-contains', kind: OptionKind.RepeatableOptionalStringParam },
    { name: '--no-merged', kind: OptionKind.RepeatableOptionalStringParam },
    { name: '--points-at', kind: OptionKind.OptionalStringParam },
    { name: '--remotes', kind: OptionKind.Flag },
    { name: '--show-current', kind: OptionKind.Flag },
    { name: '--sort', kind: OptionKind.RepeatableString },
    { name: '--verbose', kind: OptionKind.RepeatableFlag },
    // BranchOptions
    { name: '--copy', kind: OptionKind.Flag },
    { name: '--create-reflog', kind: OptionKind.Flag },
    { name: '--delete', kind: OptionKind.Flag },
    { name: '--force', kind: OptionKind.Flag },
    { name: '--list', kind: OptionKind.Flag },
    { name: '--move', kind: OptionKind.Flag },
    { name: '--no-create-reflog', kind: OptionKind.Flag },
    { name: '--no-track', kind: OptionKind.Flag },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--recurse-submodules', kind: OptionKind.Flag },
    { name: '--set-upstream-to', kind: OptionKind.String },
    { name: '--track', kind: OptionKind.OptionalString },
    { name: '--unset-upstream', kind: OptionKind.Flag },
  ]],
  ['checkout', [
    { name: '-b', kind: OptionKind.NamedStrings },
    { name: '-l', kind: OptionKind.Flag },
    { name: '--detach', kind: OptionKind.Flag },
    { name: '--force', kind: OptionKind.Flag },
    { name: '--ignore-skip-worktree-bits', kind: OptionKind.Flag },
    { name: '--merge', kind: OptionKind.Flag },
    { name: '--no-progress', kind: OptionKind.Flag },
    { name: '--no-track', kind: OptionKind.Flag },
    { name: '--orphan', kind: OptionKind.NamedStrings },
    { name: '--ours', kind: OptionKind.Flag },
    { name: '--progress', kind: OptionKind.Flag },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--thiers', kind: OptionKind.Flag },
    { name: '--track', kind: OptionKind.OptionalString },
  ]],
  ['cherry-pick', [
    { name: '--abort', kind: OptionKind.Flag },
    { name: '--allow-empty', kind: OptionKind.Flag },
    { name: '--allow-empty-message', kind: OptionKind.Flag },
    { name: '--cleanup', kind: OptionKind.String },
    { name: '--continue', kind: OptionKind.Flag },
    { name: '--ff', kind: OptionKind.Flag },
    { name: '--gpg-sign', kind: OptionKind.OptionalString },
    { name: '--keep-redundant-commits', kind: OptionKind.Flag },
    { name: '--mainline', kind: OptionKind.NumericParam },
    { name: '--no-commit', kind: OptionKind.Flag },
    { name: '--no-gpg-sign', kind: OptionKind.Flag },
    { name: '--no-rerere-autoupdate', kind: OptionKind.Flag },
    { name: '--quit', kind: OptionKind.Flag },
    { name: '--rerere-autoupdate', kind: OptionKind.Flag },
    { name: '--signoff', kind: OptionKind.Flag },
    { name: '--skip', kind: OptionKind.Flag },
    { name: '--strategy', kind: OptionKind.String },
    { name: '--strategy-option', kind: OptionKind.String },
    { name: '-x', kind: OptionKind.Flag },
  ]],
  ['clone', [
    { name: '--bare', kind: OptionKind.Flag },
    { name: '--branch', kind: OptionKind.StringParam },
    { name: '--config', kind: OptionKind.CommaDelimitedKeyValue },
    { name: '--depth', kind: OptionKind.Numeric },
    { name: '--dissociate', kind: OptionKind.Flag },
    { name: '--filter', kind: OptionKind.String },
    { name: '--jobs', kind: OptionKind.NumericParam },
    { name: '--local', kind: OptionKind.Flag },
    { name: '--mirror', kind: OptionKind.Flag },
    { name: '--no-checkout', kind: OptionKind.Flag },
    { name: '--no-hardlinks', kind: OptionKind.Flag },
    { name: '--no-reject-shallow', kind: OptionKind.Flag },
    { name: '--no-remote-submodules', kind: OptionKind.Flag },
    { name: '--no-shallow-submodules', kind: OptionKind.Flag },
    { name: '--no-single-branch', kind: OptionKind.Flag },
    { name: '--no-tags', kind: OptionKind.Flag },
    { name: '--origin', kind: OptionKind.StringParam },
    { name: '--progress', kind: OptionKind.Flag },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--recurse-submodules', kind: OptionKind.RepeatablePath },
    { name: '--reference', kind: OptionKind.StringParam },
    { name: '--reference-if-able', kind: OptionKind.StringParam },
    { name: '--reject-shallow', kind: OptionKind.Flag },
    { name: '--remote-submodules', kind: OptionKind.Flag },
    { name: '--separate-git-dir', kind: OptionKind.String },
    { name: '--server-option', kind: OptionKind.RepeatableString },
    { name: '--shallow-exclude', kind: OptionKind.RepeatableString },
    { name: '--shallow-since', kind: OptionKind.Date },
    { name: '--shallow-submodules', kind: OptionKind.Flag },
    { name: '--shared', kind: OptionKind.Flag },
    { name: '--single-branch', kind: OptionKind.Flag },
    { name: '--sparse', kind: OptionKind.Flag },
    { name: '--template', kind: OptionKind.String },
    { name: '--upload-pack', kind: OptionKind.StringParam },
    { name: '--verbose', kind: OptionKind.Flag },
  ]],
  ['commit', [
    { name: '--all', kind: OptionKind.Flag },
    { name: '--amend', kind: OptionKind.Flag },
    { name: '--gpg-sign', kind: OptionKind.OptionalString },
    { name: '--message', kind: OptionKind.String },
    { name: '--no-gpg-sign', kind: OptionKind.Flag },
    { name: '--quiet', kind: OptionKind.Flag },
  ]],
  ['config', [  // option order is important for config
    { name: '--local', kind: OptionKind.Flag },
    { name: '--global', kind: OptionKind.Flag },
    { name: '--system', kind: OptionKind.Flag },
    { name: '--show-scope', kind: OptionKind.Flag },
    { name: '--list', kind: OptionKind.Flag },
    { name: '--get', kind: OptionKind.StringParam },
    { name: 'set', kind: OptionKind.AnonymousKeyValue },
    { name: '--unset', kind: OptionKind.StringParam },
  ]],
  ['_diff', [
    { name: '--abbrev', kind: OptionKind.OptionalNumeric },
    { name: '--anchored', kind: OptionKind.RepeatableString },
    { name: '--binary', kind: OptionKind.Flag },
    { name: '--break-rewrites', kind: OptionKind.OptionalString },
    { name: '--check', kind: OptionKind.Flag },
    { name: '--combined-all-paths', kind: OptionKind.Flag },
    { name: '--compact-summary', kind: OptionKind.Flag },
    { name: '--cumulative', kind: OptionKind.Flag },
    { name: '--diff-algorithm', kind: OptionKind.String },
    { name: '--diff-filter', kind: OptionKind.String },
    { name: '--diff-merges', kind: OptionKind.String },
    { name: '--dirstat', kind: OptionKind.OptionalCommaDelimitedStrings },
    { name: '--dirstat-by-file', kind: OptionKind.OptionalCommaDelimitedStrings },
    { name: '--dst-prefix', kind: OptionKind.String },
    { name: '--ext-diff', kind: OptionKind.Flag },
    { name: '--find-copies', kind: OptionKind.OptionalNumeric },
    { name: '--find-copies-harder', kind: OptionKind.Flag },
    { name: '--find-object', kind: OptionKind.String },
    { name: '--find-renames', kind: OptionKind.OptionalNumeric },
    { name: '--full-index', kind: OptionKind.Flag },
    { name: '--function-context', kind: OptionKind.Flag },
    { name: '--histogram', kind: OptionKind.Flag },
    { name: '--ignore-all-space', kind: OptionKind.Flag },
    { name: '--ignore-blank-lines', kind: OptionKind.Flag },
    { name: '--ignore-cr-at-eol', kind: OptionKind.Flag },
    { name: '--ignore-matching-lines', kind: OptionKind.String },
    { name: '--ignore-space-at-eol', kind: OptionKind.Flag },
    { name: '--ignore-space-change', kind: OptionKind.Flag },
    { name: '--ignore-submodules', kind: OptionKind.OptionalString },
    { name: '--indent-heuristic', kind: OptionKind.Flag },
    { name: '--inter-hunk-context', kind: OptionKind.Numeric },
    { name: '--irreversible-delete', kind: OptionKind.Flag },
    { name: '--line-prefix', kind: OptionKind.String },
    { name: '--minimal', kind: OptionKind.Flag },
    { name: '--name-only', kind: OptionKind.Flag },
    { name: '--name-status', kind: OptionKind.Flag },
    { name: '--no-diff-merges', kind: OptionKind.Flag },
    { name: '--no-ext-diff', kind: OptionKind.Flag },
    { name: '--no-indent-heuristic', kind: OptionKind.Flag },
    { name: '--no-patch', kind: OptionKind.Flag },
    { name: '--no-prefix', kind: OptionKind.Flag },
    { name: '--no-relative', kind: OptionKind.Flag },
    { name: '--no-renames', kind: OptionKind.Flag },
    { name: '--no-rename-empty', kind: OptionKind.Flag },
    { name: '--no-textconv', kind: OptionKind.Flag },
    { name: '--numstat', kind: OptionKind.Flag },
    { name: '--output', kind: OptionKind.String },
    { name: '--output-indicator-context', kind: OptionKind.String },
    { name: '--output-indicator-new', kind: OptionKind.String },
    { name: '--output-indicator-old', kind: OptionKind.String },
    { name: '--patch', kind: OptionKind.Flag },
    { name: '--patch-with-raw', kind: OptionKind.Flag },
    { name: '--patch-with-stat', kind: OptionKind.Flag },
    { name: '--patience', kind: OptionKind.Flag },
    { name: '--pickaxe-all', kind: OptionKind.Flag },
    { name: '--pickaxe-regex', kind: OptionKind.Flag },
    { name: '--raw', kind: OptionKind.Flag },
    { name: '--relative', kind: OptionKind.OptionalString },
    { name: '--rename-empty', kind: OptionKind.Flag },
    { name: '--shortstat', kind: OptionKind.Flag },
    { name: '--src-prefix', kind: OptionKind.String },
    { name: '--stat', kind: OptionKind.OptionalString },
    { name: '--submodule', kind: OptionKind.OptionalString },
    { name: '--summary', kind: OptionKind.Flag },
    { name: '--text', kind: OptionKind.Flag },
    { name: '--textconv', kind: OptionKind.Flag },
    { name: '--unified', kind: OptionKind.Numeric },
    { name: '--word-diff', kind: OptionKind.OptionalString },
    { name: '--word-diff-regex', kind: OptionKind.String },
    { name: '-l', kind: OptionKind.Stuck },
    { name: '-z', kind: OptionKind.Flag },
    { name: '-G', kind: OptionKind.Stuck },
    { name: '-O', kind: OptionKind.Stuck },
    { name: '-R', kind: OptionKind.Flag },
    { name: '-S', kind: OptionKind.Stuck },
  ]],
  ['diff', [
    { name: '--exit-code', kind: OptionKind.Flag },
    { name: '--quiet', kind: OptionKind.Flag },
  ]],
  ['_fetch', [
    { name: '--all', kind: OptionKind.Flag },
    { name: '--append', kind: OptionKind.Flag },
    { name: '--atomic', kind: OptionKind.Flag },
    { name: '--depth', kind: OptionKind.Numeric },
    { name: '--deepen', kind: OptionKind.Numeric },
    { name: '--force', kind: OptionKind.Flag },
    { name: '--ipv4', kind: OptionKind.Flag },
    { name: '--ipv6', kind: OptionKind.Flag },
    { name: '--jobs', kind: OptionKind.Numeric },
    { name: '--keep', kind: OptionKind.Flag },
    { name: '--negotiate-only', kind: OptionKind.Flag },
    { name: '--negotiation-tip', kind: OptionKind.RepeatableString },
    { name: '--no-show-forced-updates', kind: OptionKind.Flag },
    { name: '--no-tags', kind: OptionKind.Flag },
    { name: '--prefetch', kind: OptionKind.Flag },
    { name: '--progress', kind: OptionKind.Flag },
    { name: '--prune', kind: OptionKind.Flag },
    { name: '--refetch', kind: OptionKind.Flag },
    { name: '--refmap', kind: OptionKind.RepeatableString },
    { name: '--server-option', kind: OptionKind.RepeatableString },
    { name: '--set-upstream', kind: OptionKind.Flag },
    { name: '--shallow-exclude', kind: OptionKind.RepeatableString },
    { name: '--shallow-since', kind: OptionKind.Date },
    { name: '--show-forced-updates', kind: OptionKind.Flag },
    { name: '--tags', kind: OptionKind.Flag },
    { name: '--unshallow', kind: OptionKind.Flag },
    { name: '--update-shallow', kind: OptionKind.Flag },
  ]],
  ['fetch', [
    { name: '--multiple', kind: OptionKind.Flag },
    { name: '--no-recurse-submodules', kind: OptionKind.Flag },
    { name: '--no-write-commit-graph', kind: OptionKind.Flag },
    { name: '--prune-tags', kind: OptionKind.Flag },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--recurse-submodules', kind: OptionKind.OptionalString },
    { name: '--recurse-submodules-default', kind: OptionKind.String },
    { name: '--submodule-prefix', kind: OptionKind.String },
    { name: '--update-head-ok', kind: OptionKind.Flag },
    { name: '--verbose', kind: OptionKind.Flag },
    { name: '--write-commit-graph', kind: OptionKind.Flag },
  ]],
  ['fsck', [
    { name: '--cache', kind: OptionKind.Flag },
    { name: '--connectivity-only', kind: OptionKind.Flag },
    { name: '--dangling', kind: OptionKind.Flag },
    { name: '--full', kind: OptionKind.Flag },
    { name: '--lost-found', kind: OptionKind.Flag },
    { name: '--name-objects', kind: OptionKind.Flag },
    { name: '--no-dangling', kind: OptionKind.Flag },
    { name: '--no-full', kind: OptionKind.Flag },
    { name: '--no-progress', kind: OptionKind.Flag },
    { name: '--no-reflogs', kind: OptionKind.Flag },
    { name: '--progress', kind: OptionKind.Flag },
    { name: '--root', kind: OptionKind.Flag },
    { name: '--strict', kind: OptionKind.Flag },
    { name: '--tags', kind: OptionKind.Flag },
    { name: '--unreachable', kind: OptionKind.Flag },
    { name: '--verbose', kind: OptionKind.Flag },
  ]],
  ['for-each-ref', [
    { name: '--contains', kind: OptionKind.RepeatableOptionalString },
    { name: '--count', kind: OptionKind.Numeric },
    { name: '--format', kind: OptionKind.String },
    { name: '--ignore-case', kind: OptionKind.Flag },
    { name: '--merged', kind: OptionKind.RepeatableOptionalString },
    { name: '--no-contains', kind: OptionKind.RepeatableOptionalString },
    { name: '--no-merged', kind: OptionKind.RepeatableOptionalString },
    { name: '--points-at', kind: OptionKind.OptionalStringParam },
    { name: '--sort', kind: OptionKind.RepeatableString },
  ]],
  ['init', [
    { name: '--bare', kind: OptionKind.Flag },
    { name: '--initial-branch', kind: OptionKind.String },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--separate-git-dir', kind: OptionKind.String },
    { name: '--shared', kind: OptionKind.OptionalString },
    { name: '--template', kind: OptionKind.String },
  ]],
  ['log', [
    { name: '--abbrev-commit', kind: OptionKind.Flag },
    { name: '--all', kind: OptionKind.Flag },
    { name: '--all-match', kind: OptionKind.Flag },
    { name: '--alternate-refs', kind: OptionKind.Flag },
    { name: '--ancestry-path', kind: OptionKind.Flag },
    { name: '--author', kind: OptionKind.RepeatableString },
    { name: '--author-date-order', kind: OptionKind.Flag },
    { name: '--basic-regexp', kind: OptionKind.Flag },
    { name: '--bisect', kind: OptionKind.Flag },
    { name: '--boundary', kind: OptionKind.Flag },
    { name: '--branches', kind: OptionKind.String },
    { name: '--cherry', kind: OptionKind.Flag },
    { name: '--cherry-mark', kind: OptionKind.Flag },
    { name: '--cherry-pick', kind: OptionKind.Flag },
    { name: '--children', kind: OptionKind.Flag },
    { name: '--committer', kind: OptionKind.RepeatableString },
    { name: '--date', kind: OptionKind.String },
    { name: '--date-order', kind: OptionKind.Flag },
    { name: '--decorate', kind: OptionKind.OptionalString },
    { name: '--decorate-refs', kind: OptionKind.String },
    { name: '--decorate-refs-exclude', kind: OptionKind.String },
    { name: '--dense', kind: OptionKind.Flag },
    { name: '--encoding', kind: OptionKind.String },
    { name: '--exclude', kind: OptionKind.RepeatableString },
    { name: '--exclude-first-parent-only', kind: OptionKind.Flag },
    { name: '--expand-tabs', kind: OptionKind.OptionalNumeric },
    { name: '--extended-regexp', kind: OptionKind.Flag },
    { name: '--first-parent', kind: OptionKind.Flag },
    { name: '--fixed-strings', kind: OptionKind.Flag },
    { name: '--follow', kind: OptionKind.Flag },
    { name: '--format', kind: OptionKind.String },
    { name: '--full-diff', kind: OptionKind.Flag },
    { name: '--full-history', kind: OptionKind.Flag },
    { name: '--graph', kind: OptionKind.Flag },
    { name: '--glob', kind: OptionKind.String },
    { name: '--grep', kind: OptionKind.RepeatableString },
    { name: '--grep-reflog', kind: OptionKind.RepeatableString },
    { name: '--ignore-missing', kind: OptionKind.Flag },
    { name: '--invert-grep', kind: OptionKind.Flag },
    { name: '--left-only', kind: OptionKind.Flag },
    { name: '--left-right', kind: OptionKind.Flag },
    { name: '--log-size', kind: OptionKind.Flag },
    { name: '--mailmap', kind: OptionKind.Flag },
    { name: '--max-count', kind: OptionKind.Numeric },
    { name: '--max-parents', kind: OptionKind.Numeric },
    { name: '--merge', kind: OptionKind.Flag },
    { name: '--merges', kind: OptionKind.Flag },
    { name: '--min-parents', kind: OptionKind.Numeric },
    { name: '--no-abbrev-commit', kind: OptionKind.Flag },
    { name: '--no-decorate', kind: OptionKind.Flag },
    { name: '--no-expand-tabs', kind: OptionKind.Flag },
    { name: '--no-mailmap', kind: OptionKind.Flag },
    { name: '--no-max-parents', kind: OptionKind.Flag },
    { name: '--no-merges', kind: OptionKind.Flag },
    { name: '--no-min-parents', kind: OptionKind.Flag },
    { name: '--no-notes', kind: OptionKind.Flag },
    { name: '--no-walk', kind: OptionKind.OptionalString },
    { name: '--notes', kind: OptionKind.RepeatableOptionalString },
    { name: '--oneline', kind: OptionKind.Flag },
    { name: '--parents', kind: OptionKind.Flag },
    { name: '--reflog', kind: OptionKind.Flag },
    { name: '--regexp-ignore-case', kind: OptionKind.Flag },
    { name: '--remotes', kind: OptionKind.String },
    { name: '--remove-empty', kind: OptionKind.Flag },
    { name: '--reverse', kind: OptionKind.Flag },
    { name: '--right-only', kind: OptionKind.Flag },
    { name: '--show-linear-break', kind: OptionKind.OptionalString },
    { name: '--show-pulls', kind: OptionKind.Flag },
    { name: '--show-signature', kind: OptionKind.Flag },
    { name: '--simplify-by-decoration', kind: OptionKind.Flag },
    { name: '--simplify-merges', kind: OptionKind.Flag },
    { name: '--since', kind: OptionKind.Date },
    { name: '--single-worktree', kind: OptionKind.Flag },
    { name: '--skip', kind: OptionKind.Numeric },
    { name: '--source', kind: OptionKind.Flag },
    { name: '--sparse', kind: OptionKind.Flag },
    { name: '--tags', kind: OptionKind.String },
    { name: '--topo-order', kind: OptionKind.Flag },
    { name: '--until', kind: OptionKind.Date },
    { name: '--walk-reflogs', kind: OptionKind.Flag },
    { name: '-L', kind: OptionKind.Stuck },
  ]],
  ['ls-files', [
    { name: '--abbrev', kind: OptionKind.OptionalNumeric },
    { name: '--cached', kind: OptionKind.Flag },
    { name: '--debug', kind: OptionKind.Flag },
    { name: '--deduplicate', kind: OptionKind.Flag },
    { name: '--deleted', kind: OptionKind.Flag },
    { name: '--directory', kind: OptionKind.Flag },
    { name: '--eol', kind: OptionKind.Flag },
    { name: '--error-unmatch', kind: OptionKind.Flag },
    { name: '--exclude', kind: OptionKind.String },
    { name: '--exclude-standard', kind: OptionKind.Flag },
    { name: '--format', kind: OptionKind.String },
    { name: '--full-name', kind: OptionKind.Flag },
    { name: '--ignored', kind: OptionKind.Flag },
    { name: '--killed', kind: OptionKind.Flag },
    { name: '--modified', kind: OptionKind.Flag },
    { name: '--no-empty-directory', kind: OptionKind.Flag },
    { name: '--others', kind: OptionKind.Flag },
    { name: '--recurse-submodules', kind: OptionKind.Flag },
    { name: '--sparse', kind: OptionKind.Flag },
    { name: '--stage', kind: OptionKind.Flag },
    { name: '--unmerged', kind: OptionKind.Flag },
    { name: '-z', kind: OptionKind.Flag },
  ]],
  ['merge', [
    { name: '--abort', kind: OptionKind.Flag },
    { name: '--allow-unrelated-histories', kind: OptionKind.Flag },
    { name: '--autostash', kind: OptionKind.Flag },
    { name: '--cleanup', kind: OptionKind.String },
    { name: '--commit', kind: OptionKind.Flag },
    { name: '--continue', kind: OptionKind.Flag },
    { name: '--ff', kind: OptionKind.Flag },
    { name: '--ff-only', kind: OptionKind.Flag },
    { name: '--gpg-sign', kind: OptionKind.OptionalString },
    { name: '--into-name', kind: OptionKind.StringParam },
    { name: '--log', kind: OptionKind.OptionalNumeric },
    { name: '--no-autostash', kind: OptionKind.Flag },
    { name: '--no-commit', kind: OptionKind.Flag },
    { name: '--no-ff', kind: OptionKind.Flag },
    { name: '--no-gpg-sign', kind: OptionKind.Flag },
    { name: '--no-log', kind: OptionKind.Flag },
    { name: '--no-overwrite-ignore', kind: OptionKind.Flag },
    { name: '--no-progress', kind: OptionKind.Flag },
    { name: '--no-rerere-autoupdate', kind: OptionKind.Flag },
    { name: '--no-signoff', kind: OptionKind.Flag },
    { name: '--no-squash', kind: OptionKind.Flag },
    { name: '--no-stat', kind: OptionKind.Flag },
    { name: '--no-verify', kind: OptionKind.Flag },
    { name: '--no-verify-signatures', kind: OptionKind.Flag },
    { name: '--overwrite-ignore', kind: OptionKind.Flag },
    { name: '--progress', kind: OptionKind.Flag },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--quit', kind: OptionKind.Flag },
    { name: '--rerere-autoupdate', kind: OptionKind.Flag },
    { name: '--signoff', kind: OptionKind.Flag },
    { name: '--squash', kind: OptionKind.Flag },
    { name: '--stat', kind: OptionKind.Flag },
    { name: '--strategy', kind: OptionKind.RepeatableString },
    { name: '--strategy-option', kind: OptionKind.String },
    { name: '--verbose', kind: OptionKind.Flag },
    { name: '--verify', kind: OptionKind.Flag },
    { name: '--verify-signatures', kind: OptionKind.Flag },
    { name: '-m', kind: OptionKind.StringParam },
  ]],
  ['mv', [
    { name: '--force', kind: OptionKind.Flag },
    { name: '--verbose', kind: OptionKind.Flag },
    { name: '-k', kind: OptionKind.Flag },
  ]],
  ['pull', [
    { name: '--allow-unrelated-histories', kind: OptionKind.Flag },
    { name: '--autostash', kind: OptionKind.Flag },
    { name: '--cleanup', kind: OptionKind.String },
    { name: '--commit', kind: OptionKind.Flag },
    { name: '--ff', kind: OptionKind.Flag },
    { name: '--ff-only', kind: OptionKind.Flag },
    { name: '--gpg-sign', kind: OptionKind.OptionalString },
    { name: '--log', kind: OptionKind.OptionalNumeric },
    { name: '--no-autostash', kind: OptionKind.Flag },
    { name: '--no-commit', kind: OptionKind.Flag },
    { name: '--no-ff', kind: OptionKind.Flag },
    { name: '--no-gpg-sign', kind: OptionKind.Flag },
    { name: '--no-log', kind: OptionKind.Flag },
    { name: '--no-rebase', kind: OptionKind.Flag },
    { name: '--no-recurse-submodules', kind: OptionKind.Flag },
    { name: '--no-signoff', kind: OptionKind.Flag },
    { name: '--no-squash', kind: OptionKind.Flag },
    { name: '--no-stat', kind: OptionKind.Flag },
    { name: '--no-verify', kind: OptionKind.Flag },
    { name: '--no-verify-signatures', kind: OptionKind.Flag },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--rebase', kind: OptionKind.OptionalString },
    { name: '--recurse-submodules', kind: OptionKind.OptionalString },
    { name: '--signoff', kind: OptionKind.Flag },
    { name: '--squash', kind: OptionKind.Flag },
    { name: '--stat', kind: OptionKind.Flag },
    { name: '--strategy', kind: OptionKind.RepeatableString },
    { name: '--strategy-option', kind: OptionKind.String },
    { name: '--verbose', kind: OptionKind.Flag },
    { name: '--verify', kind: OptionKind.Flag },
    { name: '--verify-signatures', kind: OptionKind.Flag },
  ]],
  ['push', [
    { name: '--all', kind: OptionKind.Flag },
    { name: '--atomic', kind: OptionKind.Flag },
    { name: '--delete', kind: OptionKind.Flag },
    { name: '--follow-tags', kind: OptionKind.Flag },
    { name: '--force', kind: OptionKind.Flag },
    { name: '--force-if-includes', kind: OptionKind.Flag },
    { name: '--force-with-lease', kind: OptionKind.OptionalString },
    { name: '--ipv4', kind: OptionKind.Flag },
    { name: '--ipv6', kind: OptionKind.Flag },
    { name: '--mirror', kind: OptionKind.Flag },
    { name: '--no-atomic', kind: OptionKind.Flag },
    { name: '--no-force-if-includes', kind: OptionKind.Flag },
    { name: '--no-force-with-lease', kind: OptionKind.Flag },
    { name: '--no-recurse-submodules', kind: OptionKind.Flag },
    { name: '--no-signed', kind: OptionKind.Flag },
    { name: '--no-thin', kind: OptionKind.Flag },
    { name: '--no-verify', kind: OptionKind.Flag },
    { name: '--porcelain', kind: OptionKind.Flag },
    { name: '--progress', kind: OptionKind.Flag },
    { name: '--prune', kind: OptionKind.Flag },
    { name: '--push-option', kind: OptionKind.RepeatableString },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--recurse-submodules', kind: OptionKind.String },
    { name: '--repo', kind: OptionKind.String },
    { name: '--set-upstream', kind: OptionKind.Flag },
    { name: '--signed', kind: OptionKind.OptionalString },
    { name: '--tags', kind: OptionKind.Flag },
    { name: '--thin', kind: OptionKind.Flag },
    { name: '--verbose', kind: OptionKind.Flag },
    { name: '--verify', kind: OptionKind.Flag },
  ]],
  ['rebase', [
    { name: '--abort', kind: OptionKind.Flag },
    { name: '--apply', kind: OptionKind.Flag },
    { name: '--autosquash', kind: OptionKind.Flag },
    { name: '--committer-date-is-author-date', kind: OptionKind.Flag },
    { name: '--continue', kind: OptionKind.Flag },
    { name: '--empty', kind: OptionKind.String },
    { name: '--fork-point', kind: OptionKind.Flag },
    { name: '--gpg-sign', kind: OptionKind.OptionalString },
    { name: '--ignore-date', kind: OptionKind.Flag },
    { name: '--ignore-whitespace', kind: OptionKind.Flag },
    { name: '--keep-base', kind: OptionKind.Flag },
    { name: '--keep-empty', kind: OptionKind.Flag },
    { name: '--merge', kind: OptionKind.Flag },
    { name: '--no-autosquash', kind: OptionKind.Flag },
    { name: '--no-ff', kind: OptionKind.Flag },
    { name: '--no-fork-point', kind: OptionKind.Flag },
    { name: '--no-gpg-sign', kind: OptionKind.Flag },
    { name: '--no-keep-empty', kind: OptionKind.Flag },
    { name: '--no-reapply-cherry-picks', kind: OptionKind.Flag },
    { name: '--no-rerere-autoupdate', kind: OptionKind.Flag },
    { name: '--no-stat', kind: OptionKind.Flag },
    { name: '--no-verify', kind: OptionKind.Flag },
    { name: '--onto', kind: OptionKind.StringParam },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--quit', kind: OptionKind.Flag },
    { name: '--reapply-cherry-picks', kind: OptionKind.Flag },
    { name: '--rebase-merges', kind: OptionKind.OptionalString },
    { name: '--rerere-autoupdate', kind: OptionKind.Flag },
    { name: '--root', kind: OptionKind.Flag },
    { name: '--signoff', kind: OptionKind.Flag },
    { name: '--skip', kind: OptionKind.Flag },
    { name: '--stat', kind: OptionKind.Flag },
    { name: '--strategy', kind: OptionKind.String },
    { name: '--strategy-option', kind: OptionKind.String },
    { name: '--verbose', kind: OptionKind.Flag },
    { name: '--verify', kind: OptionKind.Flag },
    { name: '--whitespace', kind: OptionKind.String },
    { name: '-C', kind: OptionKind.Stuck },
  ]],
  ['remote', [
    { name: '--verbose', kind: OptionKind.Flag },
  ]],
  ['reset', [
    { name: '--hard', kind: OptionKind.Flag },
    { name: '--keep', kind: OptionKind.Flag },
    { name: '--merge', kind: OptionKind.Flag },
    { name: '--mixed', kind: OptionKind.Flag },
    { name: '--no-recurse-submodules', kind: OptionKind.Flag },
    { name: '--no-quiet', kind: OptionKind.Flag },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--recurse-submodules', kind: OptionKind.Flag },
    { name: '--soft', kind: OptionKind.Flag },
  ]],
  ['restore', [
    { name: '--conflict', kind: OptionKind.String },
    { name: '--ignore-skip-worktree-bits', kind: OptionKind.Flag },
    { name: '--ignore-unmerged', kind: OptionKind.Flag },
    { name: '--merge', kind: OptionKind.Flag },
    { name: '--no-overlay', kind: OptionKind.Flag },
    { name: '--no-progress', kind: OptionKind.Flag },
    { name: '--no-recurse-submodules', kind: OptionKind.Flag },
    { name: '--ours', kind: OptionKind.Flag },
    { name: '--overlay', kind: OptionKind.Flag },
    { name: '--progress', kind: OptionKind.Flag },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--recurse-submodules', kind: OptionKind.Flag },
    { name: '--source', kind: OptionKind.String },
    { name: '--staged', kind: OptionKind.Flag },
    { name: '--thiers', kind: OptionKind.Flag },
    { name: '--worktree', kind: OptionKind.Flag },
  ]],
  ['revert', [
    { name: '--abort', kind: OptionKind.Flag },
    { name: '--cleanup', kind: OptionKind.String },
    { name: '--continue', kind: OptionKind.Flag },
    { name: '--gpg-sign', kind: OptionKind.OptionalString },
    { name: '--mainline', kind: OptionKind.NumericParam },
    { name: '--no-commit', kind: OptionKind.Flag },
    { name: '--no-gpg-sign', kind: OptionKind.Flag },
    { name: '--no-rerere-autoupdate', kind: OptionKind.Flag },
    { name: '--quit', kind: OptionKind.Flag },
    { name: '--reference', kind: OptionKind.Flag },
    { name: '--rerere-autoupdate', kind: OptionKind.Flag },
    { name: '--signoff', kind: OptionKind.Flag },
    { name: '--skip', kind: OptionKind.Flag },
    { name: '--strategy', kind: OptionKind.String },
    { name: '--strategy-option', kind: OptionKind.String },
  ]],
  ['rev-parse', [
    { name: '--abbrev-ref', kind: OptionKind.OptionalString },
    { name: '--absolute-git-dir', kind: OptionKind.Flag },
    { name: '--all', kind: OptionKind.Flag },
    { name: '--branches', kind: OptionKind.OptionalString },
    { name: '--default', kind: OptionKind.StringParam },
    { name: '--disambiguate', kind: OptionKind.String },
    { name: '--exclude', kind: OptionKind.RepeatableString },
    { name: '--flags', kind: OptionKind.Flag },
    { name: '--git-common-dir', kind: OptionKind.Flag },
    { name: '--git-dir', kind: OptionKind.Flag },
    { name: '--git-path', kind: OptionKind.StringParam },
    { name: '--glob', kind: OptionKind.String },
    { name: '--is-bare-repository', kind: OptionKind.Flag },
    { name: '--is-inside-git-dir', kind: OptionKind.Flag },
    { name: '--is-inside-work-tree', kind: OptionKind.Flag },
    { name: '--is-shallow-repository', kind: OptionKind.Flag },
    { name: '--local-env-vars', kind: OptionKind.Flag },
    { name: '--no-flags', kind: OptionKind.Flag },
    { name: '--no-revs', kind: OptionKind.Flag },
    { name: '--not', kind: OptionKind.Flag },
    { name: '--path-format', kind: OptionKind.String },
    { name: '--prefix', kind: OptionKind.StringParam },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--remotes', kind: OptionKind.OptionalString },
    { name: '--resolve-git-dir', kind: OptionKind.StringParam },
    { name: '--revs-only', kind: OptionKind.Flag },
    { name: '--shared-index-path', kind: OptionKind.Flag },
    { name: '--short', kind: OptionKind.OptionalNumeric },
    { name: '--show-cdup', kind: OptionKind.Flag },
    { name: '--show-object-format', kind: OptionKind.OptionalString },
    { name: '--show-prefix', kind: OptionKind.Flag },
    { name: '--show-superproject-working-tree', kind: OptionKind.Flag },
    { name: '--show-toplevel', kind: OptionKind.Flag },
    { name: '--symbolic', kind: OptionKind.Flag },
    { name: '--symbolic-full-name', kind: OptionKind.Flag },
    { name: '--tags', kind: OptionKind.OptionalString },
    { name: '--verify', kind: OptionKind.Flag },
  ]],
  ['rm', [
    { name: '--cached', kind: OptionKind.Flag },
    { name: '--force', kind: OptionKind.Flag },
    { name: '--ignore-unmatch', kind: OptionKind.Flag },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--sparse', kind: OptionKind.Flag },
    { name: '-r', kind: OptionKind.Flag },
  ]],
  ['show', [
    { name: '--abbrev-commit', kind: OptionKind.Flag },
    { name: '--children', kind: OptionKind.Flag },
    { name: '--date', kind: OptionKind.String },
    { name: '--encoding', kind: OptionKind.String },
    { name: '--expand-tabs', kind: OptionKind.OptionalNumeric },
    { name: '--format', kind: OptionKind.String },
    { name: '--graph', kind: OptionKind.Flag },
    { name: '--left-right', kind: OptionKind.Flag },
    { name: '--no-abbrev-commit', kind: OptionKind.Flag },
    { name: '--no-expand-tabs', kind: OptionKind.Flag },
    { name: '--no-notes', kind: OptionKind.Flag },
    { name: '--notes', kind: OptionKind.RepeatableOptionalString },
    { name: '--oneline', kind: OptionKind.Flag },
    { name: '--parents', kind: OptionKind.Flag },
    { name: '--show-linear-break', kind: OptionKind.OptionalString },
    { name: '--show-signature', kind: OptionKind.Flag },
  ]],
  ['stash', [
    { name: '--all', kind: OptionKind.Flag },
    { name: '--include-untracked', kind: OptionKind.Flag },
    { name: '--index', kind: OptionKind.Flag },
    { name: '--keep-index', kind: OptionKind.Flag },
    { name: '--no-include-untracked', kind: OptionKind.Flag },
    { name: '--no-keep-index', kind: OptionKind.Flag },
    { name: '--only-untracked', kind: OptionKind.Flag },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--staged', kind: OptionKind.Flag },
  ]],
  ['status', [
    { name: '--ahead-behind', kind: OptionKind.Flag },
    { name: '--branch', kind: OptionKind.Flag },
    { name: '--column', kind: OptionKind.OptionalString },
    { name: '--find-renames', kind: OptionKind.OptionalString },
    { name: '--ignore-submodules', kind: OptionKind.OptionalString },
    { name: '--ignored', kind: OptionKind.OptionalString },
    { name: '--long', kind: OptionKind.Flag },
    { name: '--no-ahead-behind', kind: OptionKind.Flag },
    { name: '--no-column', kind: OptionKind.Flag },
    { name: '--no-renames', kind: OptionKind.Flag },
    { name: '--porcelain', kind: OptionKind.OptionalString },
    { name: '--renames', kind: OptionKind.Flag },
    { name: '--short', kind: OptionKind.Flag },
    { name: '--show-stash', kind: OptionKind.Flag },
    { name: '--untracked-files', kind: OptionKind.OptionalString },
    { name: '--verbose', kind: OptionKind.RepeatableFlag },
    { name: '-z', kind: OptionKind.Flag },
  ]],
  ['switch', [
    { name: '--conflict', kind: OptionKind.String },
    { name: '--create', kind: OptionKind.StringParam },
    { name: '--detach', kind: OptionKind.Flag },
    { name: '--discard-changes', kind: OptionKind.Flag },
    { name: '--force-create', kind: OptionKind.StringParam },
    { name: '--ignore-other-worktrees', kind: OptionKind.Flag },
    { name: '--merge', kind: OptionKind.Flag },
    { name: '--no-progress', kind: OptionKind.Flag },
    { name: '--no-recurse-submodules', kind: OptionKind.Flag },
    { name: '--no-track', kind: OptionKind.Flag },
    { name: '--orphan', kind: OptionKind.StringParam },
    { name: '--progress', kind: OptionKind.Flag },
    { name: '--quiet', kind: OptionKind.Flag },
    { name: '--recurse-submodules', kind: OptionKind.Flag },
    { name: '--track', kind: OptionKind.OptionalStringParam },
  ]],
  ['tag', [
    { name: '-n', kind: OptionKind.OptionalStuck },
    { name: '--annotate', kind: OptionKind.Flag },
    { name: '--cleanup', kind: OptionKind.String },
    { name: '--column', kind: OptionKind.OptionalCommaDelimitedStrings },
    { name: '--contains', kind: OptionKind.RepeatableOptionalStringParam },
    { name: '--create-reflog', kind: OptionKind.Flag },
    { name: '--delete', kind: OptionKind.Flag },
    { name: '--force', kind: OptionKind.Flag },
    { name: '--format', kind: OptionKind.String },
    { name: '--ignore-case', kind: OptionKind.Flag },
    { name: '--list', kind: OptionKind.Flag },
    { name: '--local-user', kind: OptionKind.String },
    { name: '--merged', kind: OptionKind.RepeatableOptionalStringParam },
    { name: '--message', kind: OptionKind.String },
    { name: '--no-column', kind: OptionKind.Flag },
    { name: '--no-contains', kind: OptionKind.RepeatableOptionalStringParam },
    { name: '--no-create-reflog', kind: OptionKind.Flag },
    { name: '--no-merged', kind: OptionKind.RepeatableOptionalStringParam },
    { name: '--no-sign', kind: OptionKind.Flag },
    { name: '--points-at', kind: OptionKind.OptionalStringParam },
    { name: '--sign', kind: OptionKind.Flag },
    { name: '--sort', kind: OptionKind.RepeatableString },
    { name: '--verify', kind: OptionKind.Flag },
  ]],
  ['version', [
    { name: '--build-options', kind: OptionKind.Flag },
  ]],
]);

function getMapEntry(commandGroup: CommandGroup, commandName: string): CommandOption[] {
  switch (commandGroup) {

    case CommandGroup.Anx:
      return anxCommandOptions.get(commandName) ?? [];

    case CommandGroup.Git:
      return gitCommandOptions.get(commandName) ?? [];

    default:
      return [];
  }
}

export function getCommandOptions(commandGroup: CommandGroup, commandName: string): CommandOption[] {
  switch (commandGroup) {

    case CommandGroup.AnxCommon:
      return [...getMapEntry(CommandGroup.Anx, '_common'), ...getMapEntry(CommandGroup.Anx, commandName)];

    case CommandGroup.GitDiff:
      return [...getMapEntry(CommandGroup.Git, commandName), ...getMapEntry(CommandGroup.Git, '_diff')];

    case CommandGroup.GitFetch:
      return [...getMapEntry(CommandGroup.Git, '_fetch'), ...getMapEntry(CommandGroup.Git, commandName)];

    default:
      return getMapEntry(commandGroup, commandName);
  }
}
